#docker-compose.yml
version: '3.8'

volumes:
  userdb_vol:

networks:
  micro_network:
    external:
      name: micro_network

services:
  user-api:
    container_name: cuser-service
    build:
      context: .
    ports:
      - "5001:5001"
    depends_on:
      - user-db
    networks:
      - micro_network
    restart: always

  user-db:
    container_name: cuser_dbase
    image: mongodb
    ports:
      - "32000:3306"
    volumes:
      - userdb_vol:/var/lib/mongodb